- name: Package Installation - Enable gregw/i3desktop copr
  command: dnf copr enable -y gregw/i3desktop
  args:
    warn: no
  register: gregw

- name: Package Installation - Productivity Tools
  package:
    name: [
        'xfce4-terminal',
        'ranger',
	'mousepad'
    ]
    state: present

- name: Package Installation - Development Tools
  package:
    name: [
        'binutils',
    ]
    state: present

- name: Package Installation - Media
  package:
    name: [
        'flameshot'
    ]
    state: present

- name: Package Installation - System Desktop
  package:
    name: [
        'rofi',
        'nitrogen',
	'arandr',
        'dunst'
    ]
    state: present

- name: Package Installation - I3 Desktop
  package:
    name: [
        'i3-gaps',
	'i3lock',
        'i3blocks'
    ]
    state: present
  when:
    gregw.rc == 0
